#!/usr/bin/env bash
#
# smoke.sh — assert the bring-up invariants a compose file can get wrong.
#
# Not a substitute for pytest: this checks wiring, not behaviour. Run it after
# `setup-stack.sh --update-env` with the API running on the host.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
set -a
# .env is generated by setup-stack.sh, gitignored, and not present at lint
# time — nothing for shellcheck to follow.
# shellcheck disable=SC1091
. ./.env
set +a

PASS=0; FAIL=0; SKIP=0
ok()   { printf '  ✓ %s\n' "$1"; PASS=$((PASS+1)); }
bad()  { printf '  ✗ %s\n' "$1"; FAIL=$((FAIL+1)); }
skip() { printf '  ~ %s\n' "$1"; SKIP=$((SKIP+1)); }

# The API is not containerized in this repo (see README.md -> "Local
# development stack") — it always runs on the host under uvicorn's default
# port, with no MARTYROLOGY_PORT-style override for local dev (that variable
# only exists for the VPS deploy; see scripts/deploy/setup-vps-deploy-user.sh).
API="http://localhost:8000"
FGA="${MARTYROLOGY_OPENFGA_API_URL:-http://localhost:8083}"
ISSUER="${MARTYROLOGY_ZITADEL_ISSUER:-http://localhost:${ZITADEL_PORT:-8080}}"

echo "1. Zitadel discovery"
DISCOVERY_ISSUER=$(curl -sf "$ISSUER/.well-known/openid-configuration" | jq -r '.issuer')
if [[ "$DISCOVERY_ISSUER" == "$ISSUER" ]]; then
    ok "issuer is $ISSUER"
else
    bad "discovery missing or issuer mismatch: expected $ISSUER, got ${DISCOVERY_ISSUER:-none}"
fi

echo "2. OpenFGA structural tuples"
COUNT=$(curl -sf -X POST "$FGA/stores/$MARTYROLOGY_OPENFGA_STORE_ID/read" \
    -H "Authorization: Bearer $MARTYROLOGY_OPENFGA_API_TOKEN" \
    -H "Content-Type: application/json" -d '{}' | jq '.tuples | length')
if [[ "$COUNT" == "11" ]]; then
    ok "11 structural tuples"
else
    bad "expected 11 tuples, got ${COUNT:-none}"
fi

echo "3. Alembic is at head"
CUR=$(docker compose run --rm --entrypoint alembic api-migrate current 2>/dev/null | tr -d '\r')
if grep -q '(head)' <<<"$CUR"; then
    ok "alembic current is at head"
else
    bad "alembic not at head: $CUR"
fi

echo "4. API health"
if curl -sf "$API/healthz" >/dev/null; then
    ok "GET /healthz 200"
else
    bad "GET /healthz failed"
fi

echo "5. Anonymous read of a restricted edition is redacted"
# `curl -sf` yields an empty body for ANY non-2xx status, collapsing "no such
# edition" (404 — legitimately skippable when martyrology-texts isn't
# attached) and a broken redaction path (403/500 — a real failure) into the
# same "not attached" skip. Capture the status code instead (appended after a
# newline, then split off) so only a 404 skips; every other non-2xx is
# reported as a failure with the code attached.
RESP=$(curl -s -w '\n%{http_code}' \
    "$API/api/v1/elogia/edition/martyrologium_romanum_2004/01/02" 2>/dev/null)
CODE=$(tail -n1 <<<"$RESP")
BODY=$(sed '$d' <<<"$RESP")
if [[ "$CODE" == "404" ]]; then
    skip "martyrologium_romanum_2004 not attached (martyrology-texts not mounted)"
elif [[ "$CODE" != "200" ]]; then
    bad "expected 200 or 404, got $CODE"
else
    ACCESS=$(jq -r '.metadata.access // empty' <<<"$BODY")
    TEXT=$(jq -r '.elogia[0].text // "null"' <<<"$BODY")
    if [[ "$ACCESS" == "restricted-texts" && "$TEXT" == "null" ]]; then
        ok "access=restricted-texts with text=null"
    else
        bad "expected redaction, got access=$ACCESS text=$TEXT"
    fi
fi

echo
printf 'passed %d, failed %d, skipped %d\n' "$PASS" "$FAIL" "$SKIP"
[[ $FAIL -eq 0 ]]
