#!/usr/bin/env bash
#
# smoke.sh — assert the bring-up invariants a compose file can get wrong.
#
# Not a substitute for pytest: this checks wiring, not behaviour. Run it after
# `setup-stack.sh --update-env` with the API running on the host.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
# A missing/unreadable .env must fail here, with a clear cause, rather than
# surfacing later as an opaque unbound-variable error on
# MARTYROLOGY_OPENFGA_STORE_ID under `set -u`.
[[ -r ./.env ]] || { echo ".env not found or unreadable — run setup-stack.sh --update-env first" >&2; exit 1; }
set -a
# .env is generated by setup-stack.sh, gitignored, and not present at lint
# time — nothing for shellcheck to follow.
# shellcheck disable=SC1091
. ./.env
set +a

PASS=0; FAIL=0; SKIP=0
ok()   { printf '  ✓ %s\n' "$1"; PASS=$((PASS+1)); }
bad()  { printf '  ✗ %s\n' "$1"; FAIL=$((FAIL+1)); }
skip() { printf '  ~ %s\n' "$1"; SKIP=$((SKIP+1)); }

# The API is not containerized in this repo (see README.md -> "Local
# development stack") — it always runs on the host under uvicorn's default
# port, with no MARTYROLOGY_PORT-style override for local dev (that variable
# only exists for the VPS deploy; see scripts/deploy/setup-vps-deploy-user.sh).
API="http://localhost:8000"
FGA="${MARTYROLOGY_OPENFGA_API_URL:-http://localhost:8083}"
ISSUER="${MARTYROLOGY_ZITADEL_ISSUER:-http://localhost:${ZITADEL_PORT:-8080}}"

echo "1. Zitadel discovery"
DISCOVERY_ISSUER=$(curl -sf "$ISSUER/.well-known/openid-configuration" | jq -r '.issuer')
if [[ "$DISCOVERY_ISSUER" == "$ISSUER" ]]; then
    ok "issuer is $ISSUER"
else
    bad "discovery missing or issuer mismatch: expected $ISSUER, got ${DISCOVERY_ISSUER:-none}"
fi

echo "2. OpenFGA structural tuples"
# Mirrors Authz.read_tuples's request shape (page_size 100, follow
# continuation_token) rather than a single unpaginated read. The 8
# governed_by + 3 on_platform structural tuples span multiple objects, so
# this deliberately does not filter by tuple_key.object the way
# read_tuples's per-object calls do — it enumerates the whole store, same as
# before. What changes is the assertion: grant-superuser.sh's documented
# workflow adds a platform:martyrology#superuser tuple, making 12 a normal
# post-bring-up count, not a failure — so assert AT LEAST 11 rather than
# exactly 11.
COUNT=0
TOKEN=""
for _ in $(seq 1 10); do
    # No "tuple_key" key at all (not even `{}`): OpenFGA's Read API 400s on
    # an empty tuple_key object ("object type field is required ... cannot
    # be empty") but accepts a request that omits it altogether, returning
    # every tuple in the store — confirmed against a running OpenFGA.
    PAYLOAD='{"page_size":100}'
    if [[ -n "$TOKEN" ]]; then
        PAYLOAD=$(jq -n --arg t "$TOKEN" '{page_size:100, continuation_token:$t}')
    fi
    PAGE=$(curl -sf -X POST "$FGA/stores/$MARTYROLOGY_OPENFGA_STORE_ID/read" \
        -H "Authorization: Bearer $MARTYROLOGY_OPENFGA_API_TOKEN" \
        -H "Content-Type: application/json" -d "$PAYLOAD") || { COUNT=""; break; }
    COUNT=$((COUNT + $(jq '.tuples | length' <<<"$PAGE")))
    TOKEN=$(jq -r '.continuation_token // empty' <<<"$PAGE")
    [[ -n "$TOKEN" ]] || break
done
# If the loop above exhausted its 10-iteration cap while TOKEN is still
# non-empty, pagination did not finish — OpenFGA said there was more to
# read. COUNT is a partial sum in that case; treat it the same as the
# curl-failure branch above rather than let a partial read satisfy >= 11.
[[ -n "$TOKEN" ]] && COUNT=""
if [[ -n "$COUNT" && "$COUNT" -ge 11 ]]; then
    ok "$COUNT structural tuples (>= 11)"
else
    bad "expected at least 11 tuples, got ${COUNT:-none}"
fi

echo "3. Alembic is at head"
# Merge stderr into the capture: a failing `docker compose run` (e.g. the
# image not built, or the container erroring before alembic runs) previously
# had its cause discarded by 2>/dev/null, leaving only an empty/unhelpful
# "alembic not at head:" message.
CUR=$(docker compose run --rm --entrypoint alembic api-migrate current 2>&1 | tr -d '\r')
if grep -q '(head)' <<<"$CUR"; then
    ok "alembic current is at head"
else
    bad "alembic not at head: $CUR"
fi

echo "4. API health"
if curl -sf "$API/healthz" >/dev/null; then
    ok "GET /healthz 200"
else
    bad "GET /healthz failed"
fi

echo "5. Anonymous read of a restricted edition is redacted"
# `curl -sf` yields an empty body for ANY non-2xx status, collapsing "no such
# edition" (404 — legitimately skippable when martyrology-texts isn't
# attached) and a broken redaction path (403/500 — a real failure) into the
# same "not attached" skip. Capture the status code instead (appended after a
# newline, then split off) so only a 404 skips; every other non-2xx is
# reported as a failure with the code attached.
RESP=$(curl -s -w '\n%{http_code}' \
    "$API/api/v1/elogia/edition/martyrologium_romanum_2004/01/02" 2>/dev/null)
CODE=$(tail -n1 <<<"$RESP")
BODY=$(sed '$d' <<<"$RESP")
if [[ "$CODE" == "404" ]]; then
    skip "martyrologium_romanum_2004 not attached (martyrology-texts not mounted)"
elif [[ "$CODE" != "200" ]]; then
    bad "expected 200 or 404, got $CODE"
else
    ACCESS=$(jq -r '.metadata.access // empty' <<<"$BODY")
    TEXT=$(jq -r '.elogia[0].text // "null"' <<<"$BODY")
    if [[ "$ACCESS" == "restricted-texts" && "$TEXT" == "null" ]]; then
        ok "access=restricted-texts with text=null"
    else
        bad "expected redaction, got access=$ACCESS text=$TEXT"
    fi
fi

echo
printf 'passed %d, failed %d, skipped %d\n' "$PASS" "$FAIL" "$SKIP"
[[ $FAIL -eq 0 ]]
